# Generated by Django 5.1.6 on 2025-02-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300)),
                ('ans3', models.CharField(max_length=300)),
                ('ans4', models.CharField(max_length=300)),
                ('ans5', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='IPOUpcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.FileField(upload_to='home/')),
                ('company_name', models.CharField(max_length=100)),
                ('company_link', models.URLField()),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField(auto_now_add=True)),
                ('close_date', models.DateField(auto_now_add=True)),
                ('issue_size', models.CharField(max_length=50)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
