# Generated by Django 5.1.6 on 2025-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='icons',
            field=models.FileField(blank=True, null=True, upload_to='home/'),
        ),
    ]
