# Generated by Django 5.1.6 on 2025-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_broker_icons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='phone',
            new_name='Opening_charge',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='company',
            new_name='maintanance_charge',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='license_number',
            new_name='percent_delivery_brokage',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='experience_years',
            new_name='percent_interaday_brokage',
        ),
        migrations.RemoveField(
            model_name='broker',
            name='email',
        ),
        migrations.AddField(
            model_name='broker',
            name='rating',
            field=models.IntegerField(default=4, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ipoupcoming',
            name='icons',
            field=models.FileField(blank=True, null=True, upload_to='home/'),
        ),
    ]
