# Generated by Django 5.1.6 on 2025-03-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_phone_broker_opening_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='Opening_charge',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='broker',
            name='percent_delivery_brokage',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='percent_interaday_brokage',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='broker',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
