# Generated by Django 5.1.6 on 2025-03-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_broker_opening_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='rating',
            field=models.FloatField(),
        ),
    ]
